name: Release
on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: build-linux
        run: go build .

      - name: set tag name
        run: echo "::set-output name=TAGNAME::@$(git show-ref HEAD --abbrev --hash)"
        run: git show-ref HEAD --abbrev --hash
        id: setTagName
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./TheFool"
          commit: ${{ env.GITHUB_REF }}
          tag: ${{ steps.setTagName.outputs.TAGNAME }}
