name: Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: get-tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: build-linux
        run: go build . && tar -czvf TheFoolLin.tar.gz TheFool

      - name: build-windows
        run: GOOS=windows go build . && tar -czvf TheFoolWin.tar.gz TheFool.exe

      - name: set tag name
        run:  tagpfx=$(date +"%Y").$(date +"%m") && tag=${tagpfx}.$(git tag | grep "$tagpfx" | wc -l) && echo "::set-output name=TAGNAME::$tag" && git tag $tag HEAD
        id: setTagName
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./TheFoolWin.tar.gz,./TheFoolLin.tar.gz"
          commit: ${{ env.GITHUB_REF }}
          tag: ${{ steps.setTagName.outputs.TAGNAME }}
          
