name: Release
on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: build-linux
        run: go build .
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./TheFool"
          commit: ${{ env.GITHUB_REF }}
          tag: latest
